version: '3.5'
services:
  app:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./test/downloads:/app/videos
      - ./test/configs:/app/configs
    ports:
      - 5599:5599
    #you can define user but you need to create mount volumes before with correct rights
    #user: '1000:1000'
    environment:
      TZ: Europe/Paris
      CONFIG_YOUTUBEDL_CMDARGS: -o "videos/%(id)s/%(title)s.%(ext)s" --no-part --hls-use-mpegts -v
